version: '3.8'

services:
  # Backend API Service
  api:
    image: '466524003251.dkr.ecr.ap-south-1.amazonaws.com/shreeharibackend:latest'
    container_name: shreehari-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
